name: Build Tauri Linux ARM

on:
  workflow_dispatch:

jobs:
  build-tauri-linux:
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: cargo install tauri-cli --force

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            libgtk-3-dev \
            librsvg2-dev \
            libayatana-appindicator3-dev \
            build-essential \
            pkg-config \
            curl \
            file \
            wget \
            patchelf \
            libudev-dev \
            xdg-utils

      - run: npm ci
      - run: npm run build

      - run: npm run tauri build -- --bundles deb appimage

      - uses: actions/upload-artifact@v4
        with:
          name: tauri-linux-arm64
          path: |
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/deb/*.deb
